### PR TITLE
add new languge: Hebrew - israel

### PR DESCRIPTION
**Pull request by avrAhituv**
Hello friend!

A lot of many thanks for your forum - its a very very good!!
and i want to add heb languge for this plugin.

Thanks, avraham ahituv

### CODE REVIEW

**Comment by barisusakli** [comment]
Hi @avrAhituv, any reason why you didn't use the language code `he` like core nodebb? https://github.com/NodeBB/NodeBB/tree/master/public/language/he. he-il is not a selectable language in nodebb right now.

**Comment by avrAhituv** [comment]
You're right
That's my mistake

**Comment by barisusakli** [comment]
Thanks

**Comment by barisusakli** [comment]
published 3.0.1

**Pull request merged**
